<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-69H0JA5" failures="1" tests="1" name="Nopackage" time="70.917" errors="0" timestamp="2020-08-13T12:42:50 IST">
  <testcase classname="com.qait.tests.BasicCourseTest" name="verifyTravelBlogText" time="60.434">
    <failure type="java.lang.AssertionError" message="[ASSERT FAILED]: Element txt_TravelBlog not found on the BasicCourse !!!">
      <![CDATA[java.lang.AssertionError: [ASSERT FAILED]: Element txt_TravelBlog not found on the BasicCourse !!!
at org.testng.Assert.fail(Assert.java:97)
at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:146)
at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:133)
at com.qait.keywords.BasicCourseActions.textTravelBlog(BasicCourseActions.java:210)
at com.qait.tests.BasicCourseTest.verifyTravelBlogText(BasicCourseTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyTravelBlogText -->
  <testcase classname="com.qait.tests.BasicCourseTest" name="navigateToBuses" time="0.0">
    <ignored/>
  </testcase> <!-- navigateToBuses -->
  <testcase classname="com.qait.tests.BasicCourseTest" name="navigateToFlights" time="0.0">
    <ignored/>
  </testcase> <!-- navigateToFlights -->
  <testcase classname="com.qait.tests.BasicCourseTest" name="navigateToHotels" time="0.0">
    <ignored/>
  </testcase> <!-- navigateToHotels -->
  <testcase classname="com.qait.tests.BasicCourseTest" name="launchApplication" time="0.0">
    <ignored/>
  </testcase> <!-- launchApplication -->
</testsuite> <!-- Nopackage -->
